#!/bin/bash

LOG_DIR="/home/bsaiv"
APP_LFILE="application.log"
SYS_LFILE="system.log"
ERROR_PATTERN=("ERROR" "INFO" "WARN")
REPORT_FILE="/home/bsaiv/logs/log_report.txt"

echo "Analyzing logs in $LOG_DIR...">"$REPORT_FILE"
echo -e "\n**********START*********">>"$REPORT_FILE"

echo -e "\nList of log files updated in last 24 hours:">>"$REPORT_FILE"
LOG_FILES=$(find $LOG_DIR -type f -name "*.log" -mtime -1)
echo "$LOG_FILES">>"$REPORT_FILE"

for LOG_FILE in $LOG_FILES; do

    echo -e "\n">>"$REPORT_FILE"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^">>"$REPORT_FILE"
    echo "===============$LOG_FILE===============">>"$REPORT_FILE"
    echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^">>"$REPORT_FILE"

    for PATTERN in "${ERROR_PATTERN[@]}"; do
     
        #echo -e "\n--- Analyzing: $LOG_FILE ---"

#printing the number of ERROR logs
        echo -e "\nSearching $PATTERN logs in: $LOG_FILE">>"$REPORT_FILE"
        grep -c "$PATTERN" "$LOG_FILE">>"$REPORT_FILE"

#counting the ERROR logs
        echo -e "\nNumber of $PATTERN logs found in: $LOG_FILE">>"$REPORT_FILE"

        ERROR_COUNT=$(grep -c "$PATTERN" "$LOG_FILE")
        echo "$ERROR_COUNT">>"$REPORT_FILE"
       
       if [ "$ERROR_COUNT" -gt 3 ]; then
            echo "\n Action Required: More than 3 $PATTERN logs found in $LOG_FILE" 
        fi

    done

done

echo -e "\n**Log_Analysis_Completed&Report_Generated**: $REPORT_FILE"
