#!/bin/bash


LOG_DIR="/home/bsaiv"
APP_LFILE="application.log"
SYS_LFILE="system.log"

ERROR_PATTERN=("ERROR" "INFO" "WARN")

echo "Analyzing logs in $LOG_DIR..."
echo "\n**********START*********"

echo -e "\nlist of log files updated in last 24 hours:"
LOG_FILES=$(find $LOG_DIR -type f -name "*.log" -mtime -1)
echo "$LOG_FILES"

for LOG_FILE in $LOG_FILES; do

    # Check if the log file is an application log or system log
    echo -e "\nsearching ${ERROR_PATTERN[0]} logs in application logs: $LOG_FILE"
    grep -c "${ERROR_PATTERN[0]}" "$LOG_FILE"

    echo -e "\nsearching ${ERROR_PATTERN[0]} logs in application logs: $LOG_FILE"
    grep "${ERROR_PATTERN[0]}" "$LOG_FILE"

    echo -e "\nsearching ${ERROR_PATTERN[1]} logs in application logs: $LOG_FILE"
    grep -c "${ERROR_PATTERN[1]}" "$LOG_FILE"

    echo -e "\nsearching ${ERROR_PATTERN[1]} logs in application logs: $LOG_FILE"
    grep "${ERROR_PATTERN[1]}" "$LOG_FILE"

    echo -e "\nsearching ${ERROR_PATTERN[2]} logs in application logs: $LOG_FILE"
    grep -c "${ERROR_PATTERN[2]}" "$LOG_FILE"

done
